import { Nunito } from "next/font/google";
import "./globals.css";
import prisma from "@/server/db";
import Store from "./components/store";
import ToasterProvider from "./components/toasterProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const todo = await prisma.todo.findMany();
  const dataWithDateString = todo.map((item) => ({
    ...item,
    createdAt: item.createdAt.toLocaleDateString(),
    expectedDate: item.expectedDate.toLocaleDateString(),
  }));
  return (
    <html lang="en">
      <body className={`${font.className} bg-blue-200 text-white`}>
        <ToasterProvider></ToasterProvider>
        <Store data={dataWithDateString}></Store>
        {children}
      </body>
    </html>
  );
}
